### ISSUE TITLE
Error 1054: Unknown column 'bt_user' in 'where clause'

### ISSUE THREAD

**Issue by lens0021** [femiwiki/UnifiedExtensionForFemiwiki#147]
```
Error 1054: Unknown column 'bt_user' in 'where clause'
Function: MediaWiki\Block\DatabaseBlockStore::newListFromConds
Query: SELECT ipb_id,ipb_address,ipb_timestamp,ipb_auto,ipb_anon_only,ipb_create_account,ipb_enable_autoblock,ipb_expiry,ipb_deleted,ipb_block_email,ipb_allow_usertalk,ipb_parent_block_id,ipb_sitewide,ipb_by_actor,ipblocks_actor.actor_user AS `ipb_by`,ipblocks_actor.actor_name AS `ipb_by_text`,comment_ipb_reason.comment_text AS `ipb_reason_text`,comment_ipb_reason.comment_data AS `ipb_reason_data`,comment_ipb_reason.comment_id AS `ipb_reason_cid` FROM `ipblocks` JOIN `actor` `ipblocks_actor` ON ((actor_id=ipb_by_actor)) JOIN `comment` `comment_ipb_reason` ON ((comment_ipb_reason.comment_id = ipb_reason_id)) WHERE (bt_user IS NOT NULL) AND (ipb_expiry >= '20240630014324')

Backtrace:
from /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1203)
#0 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1187): Wikimedia\Rdbms\Database->getQueryException(string, integer, string, string)
#1 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1161): Wikimedia\Rdbms\Database->getQueryExceptionAndLog(string, integer, string, string)
#2 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(652): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#3 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(1350): Wikimedia\Rdbms\Database->query(Wikimedia\Rdbms\Query, string)
#4 /srv/femiwiki.com/includes/libs/rdbms/database/DBConnRef.php(119): Wikimedia\Rdbms\Database->select(array, array, array, string, array, array)
#5 /srv/femiwiki.com/includes/libs/rdbms/database/DBConnRef.php(351): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#6 /srv/femiwiki.com/includes/libs/rdbms/querybuilder/SelectQueryBuilder.php(730): Wikimedia\Rdbms\DBConnRef->select(array, array, array, string, array, array)
#7 /srv/femiwiki.com/includes/block/DatabaseBlockStore.php(901): Wikimedia\Rdbms\SelectQueryBuilder->fetchResultSet()
#8 /srv/femiwiki.com/extensions/UnifiedExtensionForFemiwiki/includes/HookHandlers/SpamEmail.php(74): MediaWiki\Block\DatabaseBlockStore->newListFromConds(array)
#9 /srv/femiwiki.com/includes/HookContainer/HookContainer.php(159): MediaWiki\Extension\UnifiedExtensionForFemiwiki\HookHandlers\SpamEmail->onIsValidEmailAddr(string, NULL)
#10 /srv/femiwiki.com/includes/HookContainer/HookRunner.php(2253): MediaWiki\HookContainer\HookContainer->run(string, array)
#11 /srv/femiwiki.com/includes/parser/Sanitizer.php(1800): MediaWiki\HookContainer\HookRunner->onIsValidEmailAddr(string, NULL)
#12 /srv/femiwiki.com/includes/user/User.php(3185): MediaWiki\Parser\Sanitizer::validateEmail(string)
#13 /srv/femiwiki.com/includes/Permissions/PermissionManager.php(1316): MediaWiki\User\User->isEmailConfirmed()
#14 /srv/femiwiki.com/includes/Permissions/PermissionManager.php(547): MediaWiki\Permissions\PermissionManager->checkActionPermissions(string, MediaWiki\User\User, array, string, boolean, MediaWiki\Title\Title)
#15 /srv/femiwiki.com/includes/Permissions/PermissionManager.php(336): MediaWiki\Permissions\PermissionManager->getPermissionErrorsInternal(string, MediaWiki\User\User, MediaWiki\Title\Title, string, boolean)
#16 /srv/femiwiki.com/includes/Permissions/UserAuthority.php(389): MediaWiki\Permissions\PermissionManager->userCan(string, MediaWiki\User\User, MediaWiki\Title\Title, string)
#17 /srv/femiwiki.com/includes/Permissions/UserAuthority.php(176): MediaWiki\Permissions\UserAuthority->internalCan(string, string, MediaWiki\Title\Title, NULL, boolean)
#18 /srv/femiwiki.com/includes/user/User.php(3414): MediaWiki\Permissions\UserAuthority->probablyCan(string, MediaWiki\Title\Title, NULL)
#19 /srv/femiwiki.com/includes/specials/pagers/PagerTools.php(48): MediaWiki\User\User->probablyCan(string, MediaWiki\Title\Title)
#20 /srv/femiwiki.com/includes/changes/ChangesList.php(909): MediaWiki\Pager\PagerTools->__construct(MediaWiki\Revision\MutableRevisionRecord, NULL, boolean, MediaWiki\HookContainer\HookRunner, MediaWiki\Title\Title, MediaWiki\Context\RequestContext, MediaWiki\Linker\LinkRenderer)
#21 /srv/femiwiki.com/includes/changes/ChangesList.php(867): ChangesList->insertPageTools(string, RecentChange)
#22 /srv/femiwiki.com/includes/changes/OldChangesList.php(146): ChangesList->insertRollback(string, RecentChange)
#23 /srv/femiwiki.com/includes/changes/OldChangesList.php(52): OldChangesList->formatChangeLine(RecentChange, array, boolean)
#24 /srv/femiwiki.com/includes/specials/SpecialRecentChanges.php(608): OldChangesList->recentChangesLine(RecentChange, boolean, integer)
#25 /srv/femiwiki.com/includes/specialpage/ChangesListSpecialPage.php(1631): MediaWiki\Specials\SpecialRecentChanges->outputChangesList(Wikimedia\Rdbms\MysqliResultWrapper, MediaWiki\Html\FormOptions)
#26 /srv/femiwiki.com/includes/specialpage/ChangesListSpecialPage.php(716): MediaWiki\SpecialPage\ChangesListSpecialPage->webOutput(Wikimedia\Rdbms\MysqliResultWrapper, MediaWiki\Html\FormOptions)
#27 /srv/femiwiki.com/includes/specials/SpecialRecentChanges.php(227): MediaWiki\SpecialPage\ChangesListSpecialPage->execute(NULL)
#28 /srv/femiwiki.com/includes/specialpage/SpecialPage.php(719): MediaWiki\Specials\SpecialRecentChanges->execute(NULL)
#29 /srv/femiwiki.com/includes/specialpage/SpecialPageFactory.php(1669): MediaWiki\SpecialPage\SpecialPage->run(NULL)
#30 /srv/femiwiki.com/includes/actions/ActionEntryPoint.php(504): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, MediaWiki\Context\RequestContext)
#31 /srv/femiwiki.com/includes/actions/ActionEntryPoint.php(145): MediaWiki\Actions\ActionEntryPoint->performRequest()
#32 /srv/femiwiki.com/includes/MediaWikiEntryPoint.php(199): MediaWiki\Actions\ActionEntryPoint->execute()
#33 /srv/femiwiki.com/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#34 {main}
```

**Comment by lens0021** [comment]
The mediawiki >= 1.42 has bt_user. Maybe this happened with:

* mediawiki 1.41
* main branch of UnifiedExtensionForFemiwiki

**Comment by lens0021** [comment]
I've only patched REL1_42. Should be applied to the main branch.

**Comment by lens0021** [comment]
> I've only patched REL1_42. Should be applied to the main branch.

#171
